# Generated by Django 4.1.13 on 2026-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver_name',
            new_name='receiver_email',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender_name',
            new_name='sender_email',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_role',
            field=models.CharField(default='Mother', max_length=50),
        ),
    ]
