# Generated by Django 4.1.13 on 2026-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('sugar_level', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('weight', models.FloatField()),
                ('symptoms', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
