# Generated by Django 6.0.5 on 2026-05-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancyrisk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
