# Generated by Django 6.0.5 on 2026-05-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('rating', models.FloatField()),
                ('availability', models.CharField(max_length=100)),
                ('profile_image', models.URLField()),
            ],
        ),
    ]
