# Generated by Django 4.1.13 on 2026-05-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DoctorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=100)),
                ('lmp_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Accepted', max_length=50)),
                ('risk_level', models.CharField(default='Low', max_length=50)),
                ('latest_vitals', models.CharField(default='BP: 120/80, HR: 75', max_length=100)),
                ('ai_status', models.CharField(default='Healthy Progress', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='doctors.doctor')),
            ],
        ),
    ]
