# Generated by Django 4.1.13 on 2026-05-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_id_doctorassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=100)),
                ('lmp_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('risk_level', models.CharField(default='Low', max_length=50)),
                ('latest_vitals', models.CharField(default='BP: 120/80, HR: 75', max_length=100)),
                ('ai_status', models.CharField(default='Healthy Progress', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='doctors.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorAssignment',
        ),
    ]
