# Generated by Django 4.1.13 on 2026-05-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorrequest_delete_doctorassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorrequest',
            name='ai_status',
        ),
        migrations.RemoveField(
            model_name='doctorrequest',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorrequest',
            name='latest_vitals',
        ),
        migrations.RemoveField(
            model_name='doctorrequest',
            name='lmp_date',
        ),
        migrations.RemoveField(
            model_name='doctorrequest',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='doctorrequest',
            name='doctor_email',
            field=models.EmailField(default='doctor@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctorrequest',
            name='doctor_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorrequest',
            name='mother_email',
            field=models.EmailField(default='mother@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctorrequest',
            name='pregnancy_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorrequest',
            name='mother_name',
            field=models.CharField(max_length=255),
        ),
    ]
